oceres_recipe_homepage:
    path:     /
    defaults: { _controller: OceresRecipeBundle:Default:index }
oceres_recipe_hellopage:
    path:     /hello/{name}
    defaults: { _controller: OceresRecipeBundle:Default:hello }
random:
	path: /random/{limit}
	defaults: {_controller: OceresRecipeBundle:Random:index }