oceres_recipe_homepage:
    path:     /
    defaults: { _controller: OceresRecipeBundle:Frontend:index }
oceres_recipe_recipepage:
    path:     /recipe/{recipeid}/{name}
    defaults: { _controller: OceresRecipeBundle:Recipe:recipe }
oceres_recipe_searchpage:
    path:     /search/
    defaults: { _controller: OceresRecipeBundle:Search:search }
random:
    path: /random/{limit}
    defaults: {_controller: OceresRecipeBundle:Random:index }